# Generated by Django 4.2.6 on 2024-01-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlle', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('number', models.ImageField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他')], upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]